server:
  port: 8020
spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:medium_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  tempDirPath: C:/Temp/medium_test/temp
  genFile:
    dirPath: C:/Temp/medium_test
